version: "3"
services:
       node-web-app:
           restart: always
           build: .
           ports:
             - "8889:3000"
           volumes:
              - ./:/code
       mongo:
             image: mongo
             volumes:
               - mongodb:/data/db
             ports:
               - '27017:27017'
volumes:
 mongodb: